-- Adaptive ISO/IEC 27001 detailed-assessment questions.
-- Full-assessment only. Branching is driven by organization profile fields.
PRAGMA foreign_keys = ON;

INSERT OR IGNORE INTO assessment_questions
(id,version_id,section_id,question_code,clause_ref,domain,question_text,purpose,expected_evidence,risk_if_missing,recommendation,criticality,weight,gate_key,is_quick,applicability_rule,sort_order,status,created_at,updated_at)
VALUES
('Q-CLD-01','VER-ISO27001-2022-RTI-1','SEC-C8','CLOUD-01','Clause 8','Cloud','Is cloud security governance defined with accountable ownership across the services used within the ISMS scope?','Assess cloud governance for organizations using cloud services.','Cloud governance standard, ownership matrix, cloud inventory.','Cloud risk decisions may be fragmented or unmanaged.','Define cloud governance ownership, policy and review cadence.','High',1.1,NULL,0,'{"field":"cloudStatus","notEmpty":true,"notEquals":"none"}',411,'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('Q-CLD-02','VER-ISO27001-2022-RTI-1','SEC-C8','CLOUD-02','Clause 8','Cloud','Are cloud-provider security responsibilities, assurance information and contractual obligations evaluated before and during use?','Assess provider-security due diligence.','Provider assessment, contracts, assurance reports, shared responsibility records.','Provider dependencies may create unmanaged control gaps.','Maintain provider due diligence and recurring assurance review.','High',1.1,NULL,0,'{"field":"cloudStatus","notEmpty":true,"notEquals":"none"}',412,'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('Q-CLD-03','VER-ISO27001-2022-RTI-1','SEC-C8','CLOUD-03','Clause 8','Cloud','Is the shared-responsibility model documented for each material cloud service and mapped to control owners?','Assess responsibility clarity.','Shared-responsibility matrix, RACI, service architecture.','Security tasks may be assumed by neither customer nor provider.','Map provider and customer responsibilities to named owners.','High',1.1,NULL,0,'{"field":"cloudStatus","notEmpty":true,"notEquals":"none"}',413,'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('Q-CLD-04','VER-ISO27001-2022-RTI-1','SEC-C8','CLOUD-04','Clause 8','Cloud','Are cloud configurations governed through approved baselines, change control and regular posture review?','Assess cloud configuration governance.','Configuration baseline, CSPM review, change records.','Misconfiguration may expose data and services.','Establish hardened baselines and recurring configuration review.','High',1.2,NULL,0,'{"field":"cloudStatus","notEmpty":true,"notEquals":"none"}',414,'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('Q-CLD-05','VER-ISO27001-2022-RTI-1','SEC-C8','CLOUD-05','Clause 8','Cloud','Are cloud security logs collected, retained, protected and reviewed according to defined monitoring requirements?','Assess cloud detection evidence.','Cloud audit logs, SIEM ingestion, retention settings, monitoring rules.','Cloud activity may not be traceable during incidents or audits.','Define cloud logging coverage, retention and monitoring responsibilities.','High',1.2,NULL,0,'{"field":"cloudStatus","notEmpty":true,"notEquals":"none"}',415,'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('Q-CLD-06','VER-ISO27001-2022-RTI-1','SEC-C8','CLOUD-06','Clause 8','Cloud','Are cloud backup and recovery arrangements tested against business recovery requirements?','Assess cloud resilience.','Backup policies, recovery tests, RTO/RPO evidence.','Cloud data or services may not recover within business needs.','Test backup restoration and align recovery targets with business requirements.','High',1.2,NULL,0,'{"field":"cloudStatus","notEmpty":true,"notEquals":"none"}',416,'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),

('Q-SUP-01','VER-ISO27001-2022-RTI-1','SEC-C8','SUPPLIER-01','Clause 8','Third Party','Are outsourced IT and critical technology suppliers subject to security due diligence before engagement?','Assess supplier onboarding risk.','Supplier risk assessment, due diligence records.','High-risk suppliers may be onboarded without adequate assurance.','Implement risk-based supplier security due diligence.','High',1.1,NULL,0,'{"field":"outsourcedIt","equals":true}',421,'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('Q-SUP-02','VER-ISO27001-2022-RTI-1','SEC-C8','SUPPLIER-02','Clause 8','Third Party','Do supplier contracts contain information-security, incident, audit, confidentiality and data-handling obligations appropriate to risk?','Assess contractual protection.','Contracts, security schedules, DPA, right-to-audit clauses.','Required security obligations may be unenforceable.','Standardize risk-based supplier security clauses.','High',1.1,NULL,0,'{"field":"outsourcedIt","equals":true}',422,'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('Q-SUP-03','VER-ISO27001-2022-RTI-1','SEC-C8','SUPPLIER-03','Clause 8','Third Party','Are security-related service levels and responsibilities defined and monitored for material suppliers?','Assess supplier operational assurance.','SLA/KPI, service review records, issue logs.','Supplier security performance may deteriorate without detection.','Define measurable security obligations and recurring service review.','Medium',1,NULL,0,'{"field":"outsourcedIt","equals":true}',423,'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('Q-SUP-04','VER-ISO27001-2022-RTI-1','SEC-C8','SUPPLIER-04','Clause 8','Third Party','Are material supplier security risks and changes monitored throughout the relationship?','Assess ongoing supplier monitoring.','Periodic reviews, assurance updates, change notifications.','Changes in supplier posture may introduce unmanaged risk.','Establish periodic risk-based supplier monitoring.','High',1.1,NULL,0,'{"field":"outsourcedIt","equals":true}',424,'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('Q-SUP-05','VER-ISO27001-2022-RTI-1','SEC-C8','SUPPLIER-05','Clause 8','Third Party','Are supplier exit, data return/deletion, access revocation and continuity arrangements defined?','Assess secure supplier termination.','Exit plan, termination checklist, data deletion evidence.','Residual access or data may remain after termination.','Define and test secure supplier exit requirements.','High',1.1,NULL,0,'{"field":"outsourcedIt","equals":true}',425,'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),

('Q-REM-01','VER-ISO27001-2022-RTI-1','SEC-C8','REMOTE-01','Clause 8','Remote Work','Are remote-access methods approved, strongly authenticated and limited according to business need?','Assess remote access security.','Remote access policy, MFA/VPN/ZTNA settings, access reviews.','Remote access may become an uncontrolled attack path.','Enforce approved secure remote access and strong authentication.','High',1.2,NULL,0,'{"field":"remoteWorking","equals":true}',431,'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('Q-REM-02','VER-ISO27001-2022-RTI-1','SEC-C8','REMOTE-02','Clause 8','Remote Work','Are endpoints used for remote work managed with security baselines, patching, malware protection and monitoring?','Assess endpoint safeguards.','Endpoint management, EDR, patch and compliance reports.','Unmanaged endpoints may expose organizational information.','Apply centrally managed endpoint protection and compliance monitoring.','High',1.2,NULL,0,'{"field":"remoteWorking","equals":true}',432,'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('Q-REM-03','VER-ISO27001-2022-RTI-1','SEC-C7','REMOTE-03','Clause 7','Remote Work','Are remote-work security requirements documented and communicated to relevant personnel?','Assess remote-work governance and awareness.','Remote-work policy, acknowledgement, awareness evidence.','Personnel may follow inconsistent security practices outside controlled locations.','Document and communicate role-appropriate remote-work security requirements.','Medium',1,NULL,0,'{"field":"remoteWorking","equals":true}',433,'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('Q-REM-04','VER-ISO27001-2022-RTI-1','SEC-C8','REMOTE-04','Clause 8','Remote Work','Are remote sessions, devices and access patterns monitored for anomalous or unauthorized activity?','Assess remote-work monitoring.','Authentication logs, SIEM use cases, endpoint telemetry.','Compromised remote access may remain undetected.','Monitor remote access and endpoint signals using risk-based detection rules.','High',1.1,NULL,0,'{"field":"remoteWorking","equals":true}',434,'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
